[package]
name = "clify"
version = "0.1.0"
authors = ["s4kk"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.14.1"
clap = "3.0.0-beta.2"
rand = "0.8.3"
